djangonautic/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = "accounts"

urlpatterns = [
	url(r'^signup/$', views.signup_view, name="signup")
]

djangonautic/articles/urls.py
from django.conf.urls import url
from . import views

app_name = "articles"

urlpatterns = [
	url(r'^$', views.article_list, name="list"),
	url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail")
]

djangonautic/djangonautic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^accounts/', include("accounts.urls")),
	url(r'^articles/', include("articles.urls")),
	url(r'^about/$', views.about),
	url(r'^$', views.homepage),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangonautic/accounts/models.py
from django.db import models

# Create your models here.

djangonautic/articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
	title = models.CharField(max_length=100)
	slug = models.SlugField()
	body = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	thumb = models.ImageField(default="default.png", blank=True)
	# Add in author later

	def __str__(self):
		return self.title

	def snippet(self):
		return self.body[:50] + "..."


# python manage.py makemigrations
# python manage.py migrate

djangonautic/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def signup_view(request):
	if request.method == "POST":
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			#log the user in
	form = UserCreationForm()
	return render(request, "accounts/signup.html", { 'form': form })

djangonautic/articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse

# Create your views here.
def article_list(request):
	articles = Article.objects.all().order_by("date")
	return render(request, "articles/article_list.html", { "articles": articles })

def article_detail(request, slug):
	# return HttpResponse(slug)
	article = Article.objects.get(slug=slug)
	return render(request, "articles/article_detail.html", { "article": article })

djangonautic/djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def about(request):
	# return HttpResponse("about")
	return render(request, "homepage.html")

def homepage(request):
	# return HttpResponse("homepage")
	return render(request, "about.html")

djangonautic/accounts/templates/accounts/signup.html
{% extends "base_layout.html" %}

{% block content %}
	<h1>Signup</h1>
	<form class="site-form" method="post" action="/accounts/signup">
		{{ form }}
		<input type="submit" value="Signup">
	</form>
{% endblock content %}

djangonautic/articles/templates/articles/article_detail.html
{% extends "base_layout.html" %}

{% block content %}

<div class="article-detail">
	<div class="article">
		<img src="{{ article.thumb.url }}" alt="">
		<h2>{{ article.title }}</h2>
		<p>{{ article.body }}</p>
		<p>{{ article.date }}</p>
	</div>
</div>

{% endblock content %}

djangonautic/articles/templates/articles/article_list.html
{% extends "base_layout.html" %}

{% block content %}

	<h1>Article List</h1>
	<div class="articles">
		{% for article in articles %}
			<div class="article">
				<h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
				<p>{{ article.snippet }}</p>
				<p>{{ article.date }}</p>
			</div>
		{% endfor %}
	</div>

{% endblock content %}

djangonautic/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>About</title>
</head>
<body>
	<h1>About Us</h1>
	<p>We like django</p>
</body>
</html>

djangonautic/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="{% static 'styles.css' %}">
	<title>Articles</title>
</head>
<body>
	<h1><a href="{% url 'articles:list' %}"><img src="{% static 'logo.png' %}" alt=""></a></h1>
	<div class="wrapper">
		{% block content %}
		{% endblock %}
	</div>
</body>
</html>

djangonautic/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Homepage</title>
</head>
<body>
	<h1>This is the homepage</h1>
	<p>Welcome to Djangonautic</p>
</body>
</html>